name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate config file
        run: |
          mkdir -p dist
          echo "const BASE_URL = '${{ secrets.BASE_URL }}';" > dist/env.js
          echo "const TOKEN = '${{ secrets.INITIAL_TOKEN }}';" >> dist/env.js
          echo "export { BASE_URL, INITIAL_TOKEN };" >> dist/env.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          keep_files: true
